
import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import { NavigationMenuDemo } from "./_components/Navbar/Navbar";
import { Toaster } from "@/components/ui/sonner"

import WrapperCom from "./_components/WrapperCom";
import TanSatckProvider from "@/providers/TanSatckProvider";


const exo = Exo({
  subsets: ["latin"],
  weight:['400','500']
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
     
    >
    <body  className={exo.className}>
    
    <div className="container max-w-[1400px] mx-auto">
    <TanSatckProvider>
    <WrapperCom>
      <NavigationMenuDemo />
    </WrapperCom>

    {children}
    < Toaster/>

</TanSatckProvider>
</div>
</body>
    </html>
  );
}
